// <auto-generated />
namespace HammerSpace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SeeddataandfirstrunaftermergingGameandMoviebranches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeeddataandfirstrunaftermergingGameandMoviebranches));
        
        string IMigrationMetadata.Id
        {
            get { return "202101130558283_Seed data and first run after merging Game and Movie branches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
